apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: order-management-ci

spec:

  params:
    - name: git-url
      type: string

    - name: revision
      type: string

    - name: image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/order-app/order-management

  workspaces:

    - name: source

  tasks:

    #
    # Clone
    #
    - name: clone

      taskRef:
        name: git-clone

      params:

        - name: URL
          value: $(params.git-url)

        - name: REVISION
          value: $(params.revision)

        - name: DELETE_EXISTING
          value: "true"

      workspaces:

        - name: output
          workspace: source

    #
    # Test
    #
    - name: unittest

      runAfter:
        - clone

      taskRef:
        name: unittest

      workspaces:

        - name: source
          workspace: source
    - name: build-image

      runAfter:
        - unittest

      taskRef:
        name: buildah

      params:

        - name: IMAGE
          value: "$(params.image):$(params.revision)"

        - name: DOCKERFILE
          value: "./Dockerfile"

        - name: CONTEXT
          value: "."

        - name: STORAGE_DRIVER
          value: "vfs"

        - name: FORMAT
          value: "docker"

        - name: TLS_VERIFY
          value: "false"

        - name: SKIP_PUSH
          value: "false"

        - name: BUILD_ARGS
          value: [ ]

        - name: BUILD_EXTRA_ARGS
          value: ""

        - name: PUSH_EXTRA_ARGS
          value: ""

        - name: VERBOSE
          value: "true"

      workspaces:

        - name: source
          workspace: source