apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: order-management-template

spec:
  params:
    - name: git-url
    - name: revision
    - name: image
      default: image-registry.openshift-image-registry.svc:5000/order-app/order-management

  resourcetemplates:

    - apiVersion: tekton.dev/v1
      kind: PipelineRun

      metadata:
        generateName: order-management-

      spec:
        pipelineRef:
          name: order-management-ci

        taskRunTemplate:
          serviceAccountName: pipeline

        params:
          - name: git-url
            value: $(tt.params.git-url)

          - name: revision
            value: $(tt.params.revision)

          - name: image
            value: $(tt.params.image)

        workspaces:
          - name: source

            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce

                resources:
                  requests:
                    storage: 2Gi